version: "3"
services:

  postgres:
    image: postgres:11-alpine
    env_file:
      - ./.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
