version: "3"
services:

  # app:
  #   container_name: dangout_backend
  #   image: node:lts-alpine
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ../backend:/usr/app
  #     - ./start.sh:/start.sh
  #     # - ../backend/package.json:/package.json
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - postgres
  #   command: sh start.sh
  #   env_file:
  #     - ./.env

  postgres:
    container_name: dangout_postgres
    image: postgres:11-alpine
    env_file:
      - ./.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: dangout_adminer
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
